import { useState } from 'react';

const projects = [
  { title: 'AIO Restaurant Platform', url: 'https://www.aioapp.com/', meta: 'Platform architecture · Mobile · Integrations', detail: 'All in one AI restaurant management ecosystem serving 30 plus live restaurant locations across operations, inventory, accounting, analytics, and integrations.', category: 'platform mobile', art: <><span className="orb" /><span className="device"><i /><i /><i /><b>aio</b><small>Everything a restaurant<br />needs to run smarter.</small></span></> },
  { title: 'Ultrasound.ai', url: 'https://ultrasound.ai/', meta: 'AI · Machine learning · Healthcare', detail: 'AI powered ultrasound platform for early stage pregnancy prediction using machine learning.', category: 'ai platform', art: <span className="scan">ULTRA<br /><b>SOUND</b><small>Machine learning for<br />earlier pregnancy insight.</small></span>, color: 'coral' },
  { title: 'LetsData.io', url: 'https://letsdata.io/', meta: 'Next.js · Performance · UX', detail: 'Public facing product site rebuilt end to end in Next.js for improved performance, UX, and maintainability.', category: 'ai platform', art: <span className="poster">LET’S<span>DATA</span><small>Public data,<br />made useful.</small></span>, color: 'blue' },
  { title: 'Imateam', url: 'https://imateam.us/', meta: 'React Native · Social', detail: 'Social platform enabling players to connect, collaborate, manage profiles, and build community.', category: 'mobile', art: <span className="team-mark">iM<br />TEAM<small>find your people.<br />play together.</small></span>, color: 'pink' },
  { title: 'Healing Trauma', url: 'https://healingtrauma.co.kr/', meta: 'Research platform · Healthcare', detail: 'Research platform supporting licensed clinicians and researchers studying trauma.', category: 'ai platform', art: <span className="ticket">HEALING<small>Research tools for<br />care and understanding.</small></span>, color: 'mint' },
];

const architecture = {
  edge: ['01 / 05', 'Client & edge', 'Fast, secure entry points with responsive clients, authentication, CDN delivery, and thoughtful API boundaries.', ['React, Next.js & React Native', 'CloudFront & Cognito', 'REST, GraphQL & OAuth']],
  api: ['02 / 05', 'API gateway', 'A clear front door for services: authentication, rate limiting, request shaping, and predictable contracts for every client.', ['API design & versioning', 'Authentication & authorization', 'Rate limits & observability']],
  services: ['03 / 05', 'Domain services', 'Business workflows belong in focused services with explicit ownership, robust validation, and boundaries that stay understandable.', ['NestJS & .NET services', 'Domain driven boundaries', 'Caching & async processing']],
  data: ['04 / 05', 'Data & events', 'Events decouple work that should not block a user request. Data stores are chosen deliberately for the access pattern they serve.', ['Kafka, SQS & webhooks', 'RDS, MongoDB & Redis', 'Analytics with Redshift & Athena']],
  ops: ['05 / 05', 'Cloud operations', 'Production needs feedback loops. I build systems with deployment pipelines, monitoring, tracing, and recovery in mind from the start.', ['AWS Lambda, ECS & EC2', 'CloudWatch & OpenTelemetry', 'CI/CD, Docker & Kubernetes']],
};

export default function Home({ nav }) {
  const [filter, setFilter] = useState('all');
  const [layer, setLayer] = useState('edge');
  const active = architecture[layer];
  return <main>
    <section className="hero" id="home">
      {nav}<div className="nav-spacer" />
      <div className="hero-content wrap"><p className="eyebrow rust">Senior full stack engineer · Doha, Qatar</p><h1>Building products<br />that <em>perform.</em></h1><p className="hero-copy">I’m Shoaib Ali, a product focused engineer who takes ambitious web and mobile products from system design to production.</p><div className="hero-actions"><a className="button yellow" href="#/work">Explore my work <b>↓</b></a><a className="button dark" href="mailto:shoaibintech@gmail.com">Let’s talk <b>↗</b></a></div></div>
      <div className="code-card image-left">const product = {'{'}<br />&nbsp;reliable: <b>true</b>,<br />&nbsp;scalable: <b>true</b>,<br />&nbsp;human: <b>true</b><br />{'}'}</div>
      <div className="hero-image portrait image-right"><img src="assets/shoaib-ali-portrait.png" alt="Portrait of Shoaib Ali" /></div>
      <div className="stats wrap"><div><strong>5+</strong><span>Years shipping<br />production systems</span></div><div><strong>30+</strong><span>Client projects<br />delivered end to end</span></div><div><strong>10×</strong><span>Scale enabled<br />for a core platform</span></div></div>
    </section>

    <section className="intro wrap" id="about"><p className="eyebrow">About me</p><div className="intro-grid"><h2>From the first sketch<br />to the <span>production release.</span></h2><div><p>My work sits where product thinking and practical engineering meet. I build resilient systems across frontend, backend, cloud infrastructure, and mobile.</p><a className="text-link" href="#/experience">See my experience <b>↓</b></a></div></div></section>

    <section className="work-section" id="work"><div className="wrap section-heading"><div><p className="eyebrow">Selected work</p><h2>Products built to<br />solve real problems.</h2></div><div className="filters">{[['all', 'All work'], ['platform', 'Platforms'], ['ai', 'AI & data'], ['mobile', 'Mobile']].map(([key, label]) => <button key={key} className={`filter ${filter === key ? 'active' : ''}`} onClick={() => setFilter(key)}>{label}</button>)}</div></div><div className="project-grid wrap">{projects.filter(project => filter === 'all' || project.category.includes(filter)).map((project, index) => <article className={`project ${index === 0 ? 'project-large' : ''}`} key={project.title}><a href={project.url} target="_blank" rel="noreferrer" aria-label={`Open ${project.title}`} className={`project-art ${index === 0 ? 'lavender' : project.color}`}>{project.art}</a><div className="project-meta"><div><p>{project.meta}</p><h3>{project.title}</h3></div><span>0{index + 1}</span></div><p className="project-detail">{project.detail}</p></article>)}</div></section>

    <section className="experience wrap" id="experience"><div><p className="eyebrow">Career path</p><h2>Building with ownership<br />at every stage.</h2></div><div className="timeline"><article><span>2024 to 2026</span><div><h3>AIO Restaurant Platform</h3><p className="role">Senior Full Stack Engineer · Islamabad, Pakistan</p><p>Led architecture across a multi tenant restaurant platform, building core inventory, accounting, analytics, and operations modules. Cut average API response time by 80% through database optimization, caching, indexing, and asynchronous processing.</p></div></article><article><span>2023</span><div><h3>LetsData.io</h3><p className="role">Frontend Engineer · Remote</p><p>Led an end to end rebuild of the public site in Next.js with a focus on performance, SEO, responsive UI, and maintainability.</p></div></article><article><span>2022 to 2023</span><div><h3>Esquall Technologies</h3><p className="role">Full Stack Developer · Rawalpindi, Pakistan</p><p>Delivered fintech, music commerce, and social products while mentoring junior engineers and establishing reusable frontend architecture practices.</p></div></article><article><span>2021 to 2022</span><div><h3>Creadios</h3><p className="role">Junior React & React Native Developer · Rawalpindi, Pakistan</p><p>Owned and shipped the Imateam mobile application, helping players connect, socialize, manage profiles, and coordinate activities through a social platform.</p></div></article></div></section>

    <section className="architecture" id="architecture"><div className="wrap"><div className="architecture-heading"><div><p className="eyebrow">Architecture lab</p><h2>Systems designed<br />to <span>keep moving.</span></h2></div><p>Explore the patterns I use to build production systems that remain observable, resilient, and ready to scale.</p></div><div className="architecture-lab"><div className="system-map">{Object.entries(architecture).map(([key, value]) => <button key={key} className={`arch-node ${key === 'services' ? 'node-core' : ''} ${layer === key ? 'active' : ''}`} onClick={() => setLayer(key)}>{value[1]}</button>)}</div><aside className="architecture-panel"><p className="panel-index">{active[0]}</p><h3>{active[1]}</h3><p>{active[2]}</p><ul>{active[3].map(item => <li key={item}>{item}</li>)}</ul><a className="text-link" href="#/blog">Open architecture notes <b>↗</b></a></aside></div></div></section>

    <section className="stack" id="stack"><div className="wrap"><div className="stack-heading"><p className="eyebrow">Technical toolkit</p><h2>Architecture led,<br />product minded.</h2></div><div className="skills-grid"><article><span>01</span><h3>Backend & APIs</h3><p>Node.js · NestJS · .NET · REST · GraphQL · Redis · SQS</p></article><article><span>02</span><h3>AWS & cloud</h3><p>Lambda · ECS · EC2 · S3 · RDS · CloudWatch · Cognito · Azure</p></article><article><span>03</span><h3>Data & events</h3><p>Kafka · OpenTelemetry · Grafana · Redshift · Athena · RAG</p></article><article><span>04</span><h3>Frontend & mobile</h3><p>React · Next.js · TypeScript · React Native · Redux · Tailwind</p></article></div></div></section>

    <section className="contact" id="contact"><div className="wrap contact-inner"><p className="eyebrow">Open to the right opportunity</p><h2>Let’s build something<br /><span>that lasts.</span></h2><a className="button yellow" href="mailto:shoaibintech@gmail.com">shoaibintech@gmail.com <b>↗</b></a></div></section>
  </main>;
}
